### ISSUE TITLE
seperate clickgui color and button color

### ISSUE THREAD

**Issue by seriousfrench203** [h1tm4nqq/Nhack-theme#6]
Can you make a setting that changes the button color without changing the color of the clickgui? So basically a new setting for the button color

**Comment by h1tm4nqq** [comment]
You mean there's a separate colorpicker just for clickgui?

**Comment by seriousfrench203** [comment]
i mean a seperate colorpicker for the buttons
![image](https://github.com/user-attachments/assets/86f081d9-0ed6-4963-9c84-0bce8b4b1495)
like this part if possible please

**Comment by h1tm4nqq** [comment]
added
